[env]
VC_BUILD_DIR = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"

[env.development]
TARGET_PATH = "target/debug"

[env.production]
TARGET_PATH = "target/release"
BUILD_RELEASE = "--release"

[tasks.clean-cert]
script = '''
# Remove the self-signed certificate.
if exist DriverCertificate.cer ( rm DriverCertificate.cer )
'''

[tasks.stop-driver]
ignore_errors = true
script = '''
sc stop example
sc delete example > nul 2>&1
'''

[tasks.build-driver]
dependencies = ["stop-driver"]
script = '''
cargo b %BUILD_FLAGS%
'''

[tasks.rename]
ignore_errors = true
script = '''
cd %TARGET_PATH%
move /Y dolboebdriver.dll driver.sys
'''

[tasks.sign]
dependencies = ["build-driver", "rename"]
script = '''
call "%VC_BUILD_DIR%"

if not exist DriverCertificate.cer ( makecert -r -pe -ss PrivateCertStore -n CN=DriverCertificate DriverCertificate.cer ) else ( echo Certificate already exists. )

signtool sign /a /v /s PrivateCertStore /n DriverCertificate /fd certHash /t http://timestamp.digicert.com %TARGET_PATH%/driver.sys

'''

[tasks.start-driver]
dependencies = ["sign"]
script = '''
sc.exe create example binPath=Z:\RustProjects\windows-kernel-rs\dolboebdriver\target\debug\driver.sys type=kernel
sc start example
'''